### ISSUE TITLE
test_get_new_story - AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by codexsameen** [samisnotinsane/hackernews-client#21]
This seems to be caused by a null response.

Stacktrace:
`ERROR: test_get_new_story (tests.test_hn.TestTopStories)
Traceback (most recent call last):
  File "/home/circleci/repo/tests/test_hn.py", line 109, in test_get_new_story
    new_story_items = self.client.get_new_story(fetchMax=10)
  File "/home/circleci/repo/hackernews/hn.py", line 122, in get_new_story
    new_story_items.append(self.get_item_by_id(new_story_id))
  File "/home/circleci/repo/hackernews/hn.py", line 26, in get_item_by_id
    return Item(response)
  File "/home/circleci/repo/hackernews/item.py", line 4, in __init__
    self.id = response_data.get('id')
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by codexsameen** [comment]
Fixed in PR #22
